# Generated by Django 5.2.10 on 2026-01-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField()),
                ('evolucao', models.TextField()),
                ('conduta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='consultas.consulta')),
            ],
        ),
    ]
