# Generated by Django 5.2.10 on 2026-01-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontuario',
            old_name='created_at',
            new_name='criado_em',
        ),
    ]
